import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>hey next.js!</h1>
        <h2>whatup</h2>
        <Link href="/test" >click to test!</Link>
        <Image 
          src="/images/doggo.jpeg"
          height={400}
          width={400}
          alt="doggo"
        />
      </main>
    </>
  )
}
